### ISSUE TITLE
Errors Occurred While trying WorldDreamer

### ISSUE THREAD

**Issue by BorisVandermeer** [PJLab-ADG/DriveArena#4]
1. Missing file worlddreamer/tools/description.py, without which i can't generater the key ann_fille *descriprion*.pkl

2. in GET_STARTxxx.md
``` Python
python tools/test.py resume_from_checkpoint=./dreamer_pretrained/SDv1.5_mv_single_ref_nus/weight_S200000
```
should be 
``` Python
python tools/test.py resume_from_checkpoint=./dreamer_pretrained/SDv1.5_mv_single_ref_nus/weight-S200000
```

3. incorrect key, do you mean cfg.dataset.data.val.nuscenes ?
``` bash
Traceback (most recent call last):
  File "tools/test.py", line 69, in main
    pipe, val_dataloader, weight_dtype = prepare_all(cfg)
  File "./projects/dreamer/utils/test_utils.py", line 184, in prepare_all
    val_dataset = build_dataset(
  File "/media/baixin/Data/WorkSpace/MagicDrive-video/third_party/bevfusion/mmdet3d/datasets/builder.py", line 26, in build_dataset
    elif cfg["type"] == "ConcatDataset":
KeyError: 'type'
``` 

4. requirements.txt is fromated with conda style, so that I can't use:
``` Python
pip install -r requirements.txt 
```

**Comment by jokester-zzz** [comment]
Thank you for your attention to our work. We sincerely apologize for the bugs that occurred due to our oversight.

1. First Question: We have uploaded the relevant file to address your concerns.
2. Second Question: The file path has been corrected.
3. Third Question: As we plan to support the nuPlan dataset in the future, we have made modifications to the bevfusion in the third-party directory. Unfortunately, your original environment is not compatible with our code, so you will need to install the version of bevfusion that we provide. If you only want to use simulation, you can skip the `Dataset Preparation` section.
4 . Fourth Question: We have updated the requirements.txt with the correct dependencies.

If you have any further questions, please don't hesitate to reach out. We are happy to making progress together!😄😄

**Comment by jokester-zzz** [comment]
I'm going to close this issue, please do not hesitate to reopen it if any problem occurs.
